version: "3"
services:
  yunzai-bot:
    build: .    # 使用 Dockerfile 本地构建
    # image: ccr.ccs.tencentyun.com/xm798/yunzai-bot:latest    # 使用现有镜像
    volumes:
      - $PWD/Yunzai/config.js:/app/Yunzai-Bot/config/config.js  # 映射 config.js 配置文件，配置文件中 redis 地址填写 "redis"
      - $PWD/Yunzai/logs:/app/Yunzai-Bot/logs                   # 映射日志文件
      - $PWD/Yunzai/data:/app/Yunzai-Bot/data                   # 映射数据文件
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - $PWD/redis/data:/data
      - $PWD/redis/logs:/logs
    ports:
     - "6379:6379"